In [2]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\user\anaconda3\lib\site-packages (4.0.30)

In [12]:
import pyodbc
import pandas as pd
import numpy as np
import os

server = 'proyecto.tekus.co'
port = '1433'
database = 'DataTest'
username = 'datatest'
password = '9cUQ*48AAX8Q'
try:
    conexion = pyodbc.connect('DRIVER={SQL Server};SERVER=' +
                              server+';PORT='+port+';DATABASE='+database+';UID='+username+';PWD='+ password)
except Exception as e:
    print("Ocurrió un error al conectar a SQL Server: ", e)

In [34]:
def runQuery(sql):
    try:
        with conexion.cursor() as cursor:
            cursor.execute(sql)
            return pd.DataFrame(np.array(cursor.fetchall()),
                                columns = [column[0] for column in cursor.description])
    except Exception as e:
        print("Ocurrió un error al consultar: ", e)
        return None

In [38]:
pots = runQuery("SELECT * FROM POTs ")
pots

                              PotKey              Serial CityId
0   02a5d1c69f5d44cfa9d2a256e62725a7  NOSEPEGA3000-04501    312
1   053b8b9d38d14f0097a16ff3f2df98fa  NOSEPEGA3000-06267    309
2   070fce8dd1b0443cafbbad0eccba462e  NOSEPEGA3000-08983    336
3   089e9a21a113498dbcd1274ca31d9314  NOSEPEGA3000-08606     92
4   096c10aac4214c11a67e10473671a3ca  NOSEPEGA3000-02158    367
5   09c4d9955cd24c0e97c19a765af8b014  NOSEPEGA3000-03806    289
6   0b599185f3b14688a5817d9464f90366  NOSEPEGA3000-07467    237
7   115c61b3012b41e78814f61ad72bbb15  NOSEPEGA3000-04423    316
8   11ccd89d25d14680b4d74cadf92c1c00  NOSEPEGA3000-04843    741
9   139b85b77ec94577864eb7a6ccb61cdf  NOSEPEGA3000-00614    226
10  13ebee2247fd427b809676163e4c6590  NOSEPEGA3000-03967    313
11  18aa24fd3e3b4006aa5ebdd0a7400704  NOSEPEGA3000-07775    225
12  1a4564e4e05d452996962259bb7cbf90  NOSEPEGA3000-09422    357
13  1da79dc062a1498786b5ed172362a7fc  NOSEPEGA3000-05188    226
14  1e8656f6b89c4f19bd47cb8bef23b4fa  NOSEPEGA3000-05490    231
15  1e9bf02e0c0c48438f1019717734232f  NOSEPEGA3000-03664     82
16  246983454b2d4f3081e713e524b272db  NOSEPEGA3000-01380    730
17  2771d4adc72b40348aa70131a605dd15  NOSEPEGA3000-02811     90
18  29b6ee7caa4e409eb35ab50cf763028e  NOSEPEGA3000-02441     59
19  2a8871b1fc3b4bb0a350263e6828086d  NOSEPEGA3000-09404    312
20  2a972757e72e42418a74789b4f56c180  NOSEPEGA3000-09431    266
21  2c241909eb624792ad0226844a899c12  NOSEPEGA3000-04614    317
22  2d8591c8a73840d692d1aaceb8f7e016  NOSEPEGA3000-01356    237
23  2f8ec18d8a764803b73ec9cf13d661a9  NOSEPEGA3000-01772    316
24  2fcb06120c8a47c49a45d7295aab342d  NOSEPEGA3000-01796     41
25  318c42f457ab4fd291123fd53c06f8fc  NOSEPEGA3000-04972    237
26  3196ec1df9384ad08a00abcd1bc01a97  NOSEPEGA3000-03799     82
27  31c0afa988c441c29c5c936ae985d86f  NOSEPEGA3000-08724    551
28  35fcdb980fa94f60880cac89f946ba37  NOSEPEGA3000-09267    358
29  381801b4d38c4ab3861b37db0345307f  NOSEPEGA3000-04805    367
30  3c00ba4764ae4a4da4fe882f59ab23ba  NOSEPEGA3000-07065    225
31  3deadebd599248bba29641f4a89fabb4  NOSEPEGA3000-05763     81
32  3f8a3d650fff425e8a85c42a6c6c9ec4  NOSEPEGA3000-04901    237
33  47bbe8d2878345788ccbd863c2d02df8  NOSEPEGA3000-00894     90
34  49a2b6d7021f48d2aa6b8c56c9e2471d  NOSEPEGA3000-08591    457
35  4b90ed89a1e148b59799ed7626968daf  NOSEPEGA3000-04297     90
36  4f1f7ce0016c4c98b2e39bfc193b6794  NOSEPEGA3000-06604     42
37  5f218f65be104f2f88dbb16851ea061c  NOSEPEGA3000-02798     59
38  628ded2887a64a9b8f0d53865c70e090  NOSEPEGA3000-01559    290
39  632405e8e31846ec8169fb227f37118b  NOSEPEGA3000-02946    366
40  66b8bedb0e554a6bb58ed73e323e3b28  NOSEPEGA3000-08132     54

In [37]:
cities = runQuery("SELECT * FROM Cities ")
cities

   CityId              Name
0      41            Bogotá
1      42              Cali
2      54    Rio de Janeiro
3      59      Barranquilla
4      81              Bosa
5      82         Cartagena
6      90             Bello
7      92         Girardota
8     225                NY
9     226  Ciudad de Panamá
10    231              Roma
11    237          Medellín
12    266            Madrid
13    289           Londres
14    290           Armenia
15    309     San Francisco
16    312           Murillo
17    313       Springfield
18    316             Nuquí
19    317          Montería
20    336   Rio de la plata
21    357            Cúcuta
22    358             Cusco
23    366             Pasto
24    367        San Andrés
25    457        Montevideo
26    543   Islas Margarita
27    551            Itagüí
28    730          Envigado
29    741           Pereira
30    916              Lima

In [ ]:
import os